services:
  - type: web
    name: eduquak
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PGSSL
        value: true
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash-lite
      - key: MERCADOPAGO_PUBLIC_KEY
        sync: false
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: MERCADOPAGO_CLIENT_ID
        sync: false
      - key: MERCADOPAGO_CLIENT_SECRET
        sync: false
      - key: MERCADOPAGO_REDIRECT_URI
        value: https://eduquak.onrender.com/api/mercadopago/callback
      - key: MERCADOPAGO_MODO_MARKETPLACE
        value: true
      - key: FRONTEND_URL
        value: https://eduquak.onrender.com
      - key: BACKEND_URL
        value: https://eduquak.onrender.com
      - key: COMISION_EDUQUAK
        value: 0.15
      - key: PRECIO_BASE_ASESORIA
        value: 100
      - key: PRECIO_MINIMO_ASESORIA
        value: 80
      - key: PAGOS_CONFIAR_RETORNO
        value: false
